stages:
  - test

default:
  image: rust:1.94

test:fmt:
  stage: test
  script:
    - rustup component add rustfmt
    - cargo fmt --check

test:clippy:
  stage: test
  script:
    - rustup component add clippy
    - cargo clippy --all-targets --all-features -- -D warnings

test:test:
  stage: test
  script:
    - cargo test --all-targets --all-features
